lcpp-org/RustBCA

- src/bca.rs
- src/main.rs
- src/material.rs
- src/particle.rs
- src/tests.rs
Fix to surface refraction. Surface refraction spun out into separate function for calculating the refraction angle, correctly handling sign of cos(theta). Added test that compares to Eckstein's formulation - surface refraction passes test for particles both leaving and entering surface.
> Surface refraction fix

- run_rustbca.py
- src/bca.rs
- src/main.rs
- src/material.rs
- src/particle.rs
Fix for surface refraction issue; particle leaving condition now set when it leaves the simulation boundary, not when it leaves the energy barrier. Crucial for fixing this issue was recognizing the order of operations bug which was advancing particles according to the next set of directions as opposed to the current one, leading to strange behavior at the boundary.
> Surface refraction fix; order of operations fix.

- Cargo.toml
- src/bca.rs
- src/interactions.rs
- src/main.rs
- src/material.rs
- src/tests.rs
All integer flags for controlling code have been replaced with enums. That way, the input file can have "NEWTON" instead of 0, etc. It removes a lot of uncertainty and unnecessary panics throughout the code - if given an input that is not valid member of an enum for one of those options, the code will panic when the input file is read instead of deeper in the code.
> Command line

- src/bca.rs
- src/main.rs
- src/material.rs
- src/mesh.rs
- src/tests.rs
Minor cleanup of source files through clippy suggestions. The most significant change is the removal of some explicit indexing in the bca loop and replacement with iterators. This is much safer and easier to modify.
> Minor cleanup, via clippy suggestions.

- src/bca.rs
- src/interactions.rs
- src/main.rs
- src/material.rs
- src/particle.rs
- src/tests.rs
This version allows for multiple interactions. For example, in a He on B4C situation, He-B can use a Lennard-Jones potential, B-B can use a Kr-C potential, B-C can use a ZBL potential, etc.
This requires the user to specify the interaction, scattering integral, rootfidner triplet through three matrices in the input file.
Also, this version uses enums that allow for compression of input.toml. For example, "NEWTON" is replaced with "NEWTON"={max_iterations=100, tolerance=1E-6}, allowing those options to be removed from the [options] section of the input file.
> Fancy enums

- scripts/rustbca.py
- src/bca.rs
- src/main.rs
- src/material.rs
- src/mesh.rs
- src/tests.rs
This version makes some common sense changes to the input file, and includes a minor fix to electronic stopping of compounds.
1. `energy_barrier_thickness` is now a mesh input parameter
2. `material_params `no longer has redundant `n` (number densities) option
3.  electronic stopping for compounds switched from depending on `material_params` `n` to the actual mesh densities]
4. densities in the mesh input file use the inverse cubic unit chosen - so, the default unit is "MICRON", so the default density input should be in [atoms/micron^3]
5. `energy_barrier_thickness `now uses the correct unit from the input file
> Densities and units

- scripts/formulas.py
- scripts/rustbca.py
- src/main.rs
- Update the physical constants to their 2018 CODATA values (see https://physics.nist.gov/cuu/Constants/index.html).
- Retrieve/calculate the mathematical constants using library values, giving them full double precision.
> [constants] update the values of the physical & mathematical constants

- README.md
Improve the structure and output formatting of README.md. This should greatly enhance both the readability and clarity of the first thing people see when the visit the repo. The changes include:
- Expanded/reorganized text.
- Formatted code blocks for terminal commands and Python scripts.
- Hyperlinks to Wikipedia articles for various terms/languages/packages.
- New detailed install instructions for Fedora 33.
> [docs] update README.md

- src/bca.rs
- src/material.rs
- src/mesh.rs
Fixes #64 
Uses of variable names such as `i1` have been removed from closures and replaced with meaningful names, such as `concentration`.
`cargo test` results in all tests passed.
> Removed bad variable names in closures.

- src/bca.rs
- src/main.rs
Addresses #62 
A new summary output file for use in code-coupling has been requested; the initial version of this simply includes total incident ion number, total number of sputtered material atoms, and total number of reflected ions (as neutrals) in labeled columns in a CSV file.
Additionally, fixes a warning of extraneous parentheses.
cargo test
> Added initial version of summary output file. Fixed parenthesis warning.

- src/input.rs
- src/interactions.rs
- src/main.rs
- src/output.rs
Fixes #79
This set of changes adds the source files input.rs and output.rs. This is the first of several changes designed to abstract away the non-physics aspects of the code to prepare for usage as a library.
cargo test has been run, as well as all two non-rcpr examples. This has also been tested with a handful of arbitrary input files I've had lying around.
> Abstraction layer

- src/material.rs
- src/particle.rs
- src/structs.rs
- src/tests.rs
Fixes #48
This includes a newly derived form for the surface refraction that does not rely on particle rotation. It should be much more robust than what was before, and it is easier to test.
Modified tests in tests.rs and ran layered_geometry_1D to ensure that sputtering and sputtered yields stay the same. Would like to run more tests, this is a significant change.
> New surface refraction

- src/bca.rs
- src/enums.rs
- src/material.rs
Fixes #112 
Updated surface binding model to not require the enum.
Cargo test has been run.
> Maintain backwards compat with surface binding models.

- src/geometry.rs
- src/input.rs
- src/material.rs
- src/parry.rs
- src/sphere.rs
I've removed some redundant traits; there was no need for Geometry to require implementation of the GeometryInput trait.
> Trait cleanup

- src/bca.rs
- src/geometry.rs
- src/material.rs
- src/parry.rs
- src/sphere.rs
- src/tests.rs
Cleaned up the Geometry trait. There's no need to provide nearest_to_* functions - that should be handled by the * function alone. The only mesh that was using that functionality was Mesh2D, because of the separate boundary and cells.
Additionally, ion acceleration outside materials was fixed. By moving it out of the mfp calculation, it broke; this has been addressed.
> Geometry cleanup & ion acceleration fix

- src/main.rs
Progress bar was not finishing for tiny simulations; added `bar.finish()` at end of BCA loop.
> Made sure progress bar always finishes, even for tiny simulations.

- src/lib.rs
Interaction index in lib.rs was assuming one species for compound targets
> Fixed interaction index length.

- .github/workflows/rustbca_compile_check.yml
- Cargo.toml
- setup.py
- src/lib.rs
Fixes #143 
I've made the Python bindings optional - there is a linker error present on MacOS systems, and depending on PyO3 simply isn't necessary.
Automatic testing has been done. An example C binary has been built without the Python libraries, following the instructions in the Wiki. Wiki needs to be updated still.
> Made pyo3 optional.

- RustBCA.h
Missed updating the header file. Should probably add a workflow to compile the C bindings as well as the Python bindings.
> Update to RustBCA.h.

- .github/workflows/rustbca_compile_check.yml
- setup.py
Fixes #159
Quick fix attempt - remove invocation of sudo in the setup.py installation
> Fix for Issue #159

- .github/workflows/rustbca_compile_check.yml
- examples/RustBCA.c
- examples/test_rustbca.f90
Fixes #150
I've added two examples - RustBCA.c and test_rustbca.f90 to the examples folder. Additionally, I've added compilation checks with gfortran and g++ respectively to ensure that the RustBCA libraries can be built. Next, I'll add running the test cases to the github workflow.
> Fortran example and C++ example in examples

- .github/workflows/rustbca_compile_check.yml
I'm changing the github workflow to use pip instead of directly invoking setup.py - the latter is deprecated, and hopefully this change fixes all the strange errors I've been running into using it.
> Testing pip as python build tool instead of directly invoking setup.py.

- src/bca.rs
Fixes #179
Fix to pmax; change from factor of 1/sqrt(2pi) to 1/sqrt(pi) in free flight path routine.
`cargo test` reports all tests working. I ran the 0D boron nitride example for the high and low energy cases, with interpolated electronic stopping for both, and the results are below. The fix does not appear to significantly affect the results at 1 keV, which is not unexpected, since the various geometries in Eckstein (cylindrical, spherical, planar) all have different pmaxes with little reported impact on overall results.
This is before the fix that affected ffp.
**NOTE**: I accidentally switched the colors. Doesn't impact the results.
And this is after. There is very little difference at 1 …
> Fix pmax in free-flight path routine; see issue #179.

- examples/test_rustbca.py
Fixes #193
I have added the missing slash so that the search path is now valid and can be used to locate supporting modules.
I have followed the steps mentioned in the issue, that is,
> Make a new directory, for example under /tmp, and then type python3 /full/path/to/rustbca/examples/test_rustbca.py to run the example.
After the fix, the example runs normally and gives the expected results.
OS: Fedora 36
> Fix issue #193

- scripts/rustbca.py
Fixes # (issue)
Please include a concise description of the change and how it addresses a relevant issue, including references, input files, and figures as relevant.
Please describe how the changes in this pull request have been tested, including system information such as OS.
> Updating functions in rustbca.py

- Cargo.toml
- setup.py
- src/input.rs
Fixes #216 
This quick-fix for the unusual sputtering curves observed in issue #216 when Z1>>Z2 changes the default number of weak collisions to zero.
> Urgent fix: change default number of weak collisions to zero

- src/bca.rs
- src/material.rs
- src/particle.rs
- src/tests.rs
Fixes #217 
This is another attempt at rearranging the weak collision loop for more clarity. I was unable to measure any changes to the physical results with the more correct subtraction order, but making it clear that the weak collision aren't generating fictional energy is important to long-term maintainability.
Cargo test has been run.
> Weak collision loop updates

- RustBCA.h
- examples/RustBCA.c
- src/lib.rs
Fixes #226 
It turns out that even if Rust forgets a raw pointer, it cannot be safely freed once C takes ownership. This PR adds a couple of cleanup functions that correctly dispose of structs with raw pointers when coupling to C to prevent memory leaking.
cargo test passes and RustBCA.c was used with valgrind to show that this fixes the leak. See the linked issue above.
> Memory management

- scripts/materials.py
- src/bca.rs
- src/enums.rs
- src/input.rs
- src/interactions.rs
- src/tests.rs
Merge updates from 4-8 potential version into dev.
> 4 8 potential

- src/lib.rs
Fixes #265
This PR adds vectorized versions of both the rotation functions.
Vectorized functions have been thoroughly tested in an integrated model.
> Add vectorized rotation functions

- examples/test_rustbca.py
- src/lib.rs
This PR adds a parallelized RustBCA python function, `compound_bca_list_tracked_py`. It is similar to `compound_bca_list_py`, but parallelized to as many threads are available and includes an additional output, `incident_by`, which gives the index of the incident particle any sputtered particles were sputtered by. This makes coupling to plasma models easier, as it lets the user introduce sputtered particles at the correct incident particle's location.
Documentation to come.
> Parallelized RustBCA python function for 0D compounds with tracking

- Cargo.toml
- src/lib.rs
This PR is an improvement to the vectorized rotation functions (documentation TK) that uses a parallel iterator from rayon. This doesn't offer a massive speedup on my quadcore laptop, maybe 10%, but in certain code coupling contexts this might be useful, especially when lots of cores are available. If this hurts performance, rayon offers an environment variable, `RAYON_NUM_THREADS` to turn parallelization off.
> Par rot functions

- README.md
- examples/boron_nitride_0D.toml
- examples/boron_nitride_wire_homogeneous.toml
- src/input.rs
Also fixes example comment in 2D homogeneous case, and remove unused…code from default input options.
Fixes #273 
This PR updates the README to reflect the current status of the example input files, updates the Boron Nitride 0D example to work with trajectory plotting by reducing the number of samples and enabling trajectory tracking.
Since this is going directly on main, I am also using this opportunity to remove the unused three() function previously used as a default value for serde.
Example was run using code snippet from the examples.
> Fix readme

- .github/workflows/readme_doctests.yml
- README.md
- examples/boron_nitride_0D.toml
- examples/boron_nitride_wire_homogeneous.toml
- src/input.rs
- src/lib.rs
Rotate given surface normal calculates rotations incorrectly for near-parallel incidence; I've made a change to the threshold for screening out such cases, but a more reliable fix is probably in order.
> Urgent patch to rotate_given_surface_normal

- src/interactions.rs
Fixes #280 
Replaced sigmoid with smootherstep; achieved 2X speeudp.
Tested with `test_morse.py` and `cargo test --features cpr_rootfinder`.
> Replace sigmoid with smootherstep in Kr-C-Morse.
